name: Deploy Backend to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: app-002-gen10-step3-1-py-oshima29

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (requirements.txt in repo root)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            echo "== requirements.txt =="
            sed -n '1,200p' requirements.txt
            echo "== end requirements.txt =="
            pip install --no-cache-dir -r requirements.txt
          else
            echo "no requirements.txt, skipping"
          fi

      - name: Create deployment package (zip current directory)
        run: |
          zip -r backend.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip
