name: Deploy Backend to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: app-002-gen10-step3-1-py-oshima29
      SCM_DO_BUILD_DURING_DEPLOYMENT: true  # Azureにrequirements.txtインストールさせる

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (for lint/test only)
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then
            pip install --no-cache-dir -r backend/requirements.txt
          else
            echo "no backend/requirements.txt, skipping"
          fi

      # 🔹 backend ディレクトリだけ zip
      - name: Create deployment package (backend only)
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Wait for Azure readiness
        run: sleep 30   # 再起動との衝突を回避

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip
